import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";

const APP_SRC_DIR = "src/app";
const WORKER_SRC_DIR = "src/workers";
const APP_PART_RE = /^\d{2}-.+\.js$/;
const APP_SCRIPT_PLACEHOLDER = "<!-- __KF_APP_SCRIPT__ -->";
const GENERATED_BANNER = `// Generated by scripts/prepare-public.mjs from src/app/*.js.
// Do not edit this file directly. The source fragments are ordered bundle
// parts that share one ESM scope after concatenation; they are not standalone
// browser modules.
`;

function commitSha() {
  try {
    return execFileSync("git", ["rev-parse", "--short", "HEAD"], { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}

function appParts() {
  const jsFiles = readdirSync(APP_SRC_DIR, { withFileTypes: true })
    .filter(entry => entry.isFile() && entry.name.endsWith(".js"))
    .map(entry => entry.name)
    .sort();
  const unexpected = jsFiles.filter(name => !APP_PART_RE.test(name));
  if (unexpected.length) {
    throw new Error(`Unexpected app source file(s): ${unexpected.join(", ")}. Use NN-domain-name.js so bundle order is explicit.`);
  }
  if (!jsFiles.length) throw new Error(`No app source files found in ${APP_SRC_DIR}`);
  return jsFiles;
}

function publicHtml() {
  const source = readFileSync("index.html", "utf8");
  if (!source.includes(APP_SCRIPT_PLACEHOLDER)) {
    throw new Error(`index.html is missing ${APP_SCRIPT_PLACEHOLDER}`);
  }
  return source
    .replaceAll("__COMMIT_SHA__", commitSha())
    .replace(APP_SCRIPT_PLACEHOLDER, '<script type="module" src="./app.js"></script>');
}

mkdirSync("public", { recursive: true });
mkdirSync("public/styles", { recursive: true });
mkdirSync("public/workers", { recursive: true });
writeFileSync("public/index.html", publicHtml());
copyFileSync("styles/app.css", "public/styles/app.css");
if (existsSync(WORKER_SRC_DIR)) {
  for (const entry of readdirSync(WORKER_SRC_DIR, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith(".js")) {
      copyFileSync(`${WORKER_SRC_DIR}/${entry.name}`, `public/workers/${entry.name}`);
    }
  }
}

const app = GENERATED_BANNER + appParts()
  .map(part => {
    const body = readFileSync(`${APP_SRC_DIR}/${part}`, "utf8").trimEnd();
    return `// ---- ${part} ----\n${body}\n`;
  })
  .join("\n");
writeFileSync("public/app.js", app);
execFileSync(process.execPath, ["--check", "public/app.js"], { stdio: "pipe" });
